flyway.url=jdbc:postgresql://localhost:5432/pedido_db
flyway.user=postgres
flyway.password=postgres
flyway.locations=classpath:db/migration
flyway.schemas=public
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true

pedido.rpc.port=9081

pedido.instance.id=1
pedido.cluster.nodes=1@localhost:9081,2@localhost:9082,3@localhost:9083
pagamento.rpc.host=localhost
pagamento.rpc.port=9080
