flyway.url=jdbc:h2:mem:estoque_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
flyway.user=sa
flyway.password=
flyway.locations=classpath:db/migration
flyway.schemas=PUBLIC
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true



