hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/pagamento_db
hibernate.connection.username=postgres
hibernate.connection.password=postgres
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.pool_size=10
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.use_sql_comments=true
hibernate.hbm2ddl.auto=validate
hibernate.jdbc.batch_size=20
hibernate.jdbc.fetch_size=50
hibernate.jdbc.use_scrollable_resultset=true
hibernate.generate_statistics=false
